name: run-tests

on:
  - pull_request

jobs:
  run-test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.1
          - 8.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
            path: |
                .phpstan-cache
                vendor
            key: composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer update --no-interaction

      - name: Code Styles
        run: vendor/bin/phpcs -p

      - name: Execute tests
        run: vendor/bin/phpunit
