name: run-tests

on:
  - push
  - pull_request

jobs:
  run-test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction

      - name: Configure matchers
        uses: mheap/phpunit-matcher-action@master

      - name: Code Styles
        run: vendor/bin/phpcs -p

      - name: Execute tests
        run: vendor/bin/phpunit